name: AgriIn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
   android: true
   ios: true
   image_path: "assets/ICON_APPS.png"
   adaptive_icon_background: "#789DBC"  # Warna latar belakang untuk Android
   adaptive_icon_foreground: "assets/ICON_APPS.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/title.png
    - assets/image/logosplash.png
    - assets/image/about-icon.png
    - assets/image/diagnosis-icon.png
    - assets/model/model30.tflite
    - assets/model/labels.txt
    - assets/ICON_APPS.png

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
